### ISSUE TITLE
Inspiration from AWStats

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/erddaplogs#3]
There are some nice features of AWStats that we could adopt http://www.awstats.org/

You can see it in action on GCOOS here https://boem.gcoos.org/awstats/awstats.pl

Some functionality we could adopt from this:

- [x]  bandwidth (how is this calculated?) done in #10 
- [x]  "not viewed pages" ie bots. Are they applying filters we don't have? better bot detection in #17
- [x]  Operating system done in #22 
- [x]  HTTP errors etc. done in #22 
 More? Feel free to add!

**Comment by callumrollo** [comment]
Inspired by @fgayanilo and Tuomo Saari

**Comment by fgayanilo** [comment]
AWStats features that are interesting: bandwidth, HTTP errors (400, 403,404, series), and downloads per IP

**Comment by callumrollo** [comment]
complete!
